apiVersion: v1
kind: Service
metadata:
  name: clientes-svc
  labels:
    app: clienteswebapi
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 80
    protocol: TCP
  selector:
    app: clienteswebapi
