apiVersion: v1
kind: Service
metadata:
  name: transferencias-svc
  labels:
    app: transferenciaswebapi
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    targetPort: 80
    protocol: TCP
  selector:
    app: transferenciaswebapi
