name: Clientes Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restaurar dependencias
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish de servicio
        run: dotnet publish Clientes.Web.Api/Clientes.Web.Api.csproj -c Release -o publish
      - name: Subida por Curl
        run: | 
          echo ${{secrets.TOKEN_PARA_RELEASE}}"
          echo 'alpha' > alpha.zip
          curl -X POST -H "Authorization: token ${{secrets.TOKEN_PARA_RELEASE}}" -H "Content-Type: application/zip" --data-binary @alpha.zip "https://api.github.com/repos/tresvi/CursoMicroservicios/releases"
      - name: Subir compilado
        uses: actions/upload-artifact@v3
        with:
          name: release-clientes
          path: |
            publish/**
            !publish/runtimes/**