name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restaurar Dependencias
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish Clientes
        run: dotnet publish Clientes.Web.Api/Clientes.Web.Api.csproj -c Release -o websiteClientes
      - name: Publish Transferencias
        run: dotnet publish Transferencias.Web.Api/Transferencias.Web.Api.csproj -c Release -o websiteTransferencias
      - name: Check Publish
        run: | 
          ls
          cd Transferencias.Web.Api
          ls
      - name: Subir compilado
        uses: actions/upload-artifact@v3
        with:
          name: websiteClientes
          path: websiteClientes/**