name: Transferencias Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restaurar dependencias
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish de servicio
        run: dotnet publish Transferencias.Web.Api/Transferencias.Web.Api.csproj -c Release -o publish
      - name: Subir compilado
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            publish/**
            !publish/runtimes/**

  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Descarga de artifact
        uses: actions/download-artifact@v3
        with:
          name: release
      - name: Compresion de artifact
        uses: thedoctor0/zip-release@master
        with:
          filename: build.zip
      - name: Creacion de Github release
        id: nueva-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PARA_RELEASE }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release 1.0.${{ github.run_number }} Transferencias 
      - name: Subida de assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PARA_RELEASE }}
        with:
          upload_url: ${{ steps.nueva-release.outputs.upload_url }}
          asset_path: ./build.zip
          asset_name: transferencias-build-v1.0.${{ github.run_number }}.zip
          asset_content_type: application/zip            